---
# tasks file for fail2ban

- name: install epel-release
  yum:
    name: epel-release
    state: present

- name: add epel repository gpg key
  rpm_key:
    state: present
    key: /etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-7 

- name: install fail2ban
  yum:
    name: fail2ban
    state: present
    update_cache: yes

- name: enable fail2ban service
  service:
    name: fail2ban
    state: started
    enabled: yes

- name: copy sshd.conf jail file
  copy:
    src: sshd.conf
    dest: /etc/fail2ban/jail.d/sshd.conf
  notify: restart fail2ban
